DEPARA_PGTO = Table.AddColumn(#"Tipo Alterado2", "PAGAMENTO", each if Text.Contains([COD_FORMA_PGTO], "1") then "DINHEIRO" else if Text.Contains([COD_FORMA_PGTO], "3") then "CARTÃO DÉBITO" else if Text.Contains([COD_FORMA_PGTO], "4") then "CARTÃO CRÉDITO" else if Text.Contains([COD_FORMA_PGTO], "##") then "CARTÃO PRESENTE" else if Text.Contains([COD_FORMA_PGTO], "$$") then "NÃO INFORMADO" else "NÃO CADASTRADO"),